import type { GlossaryTerm } from "@/lib/community-notes/types";

/** Topic-specific PT-PT glossaries for Portugal satellite guides. */
export const EDITORIAL_GLOSSARIES: Record<string, GlossaryTerm[]> = {
  "mezhdunarodnye-shkoly-portugaliya-2026": [
    { pt: "escola pública", ru: "государственная школа, бесплатная при наличии места в agrupamento" },
    { pt: "colégio privado", ru: "частная школа с национальной программой MEC" },
    { pt: "ensino básico", ru: "обязательное школьное образование, примерно 6–15 лет" },
    { pt: "agrupamento escolar", ru: "объединение школ района; через него идёт matrícula в público" },
    { pt: "matrícula", ru: "зачисление ребёнка в школу" },
    { pt: "comprovativo de morada", ru: "подтверждение адреса проживания" },
    { pt: "calendário de vacinação", ru: "график прививок по Plano Nacional de Vacinação" },
    { pt: "equivalência de estudos", ru: "признание предыдущего обучения при переводе между системами" },
    { pt: "exames nacionais", ru: "государственные экзамены в португальской системе secundário" },
    { pt: "waiting list", ru: "лист ожидания мест в international school" },
  ],
  "mashina-portugaliya-kupit-arenda-import-2026": [
    { pt: "DUA", context: "Documento Único Automóvel", ru: "единый документ на сделку купли-продажи авто" },
    { pt: "matrícula", ru: "государственный регистрационный номер автомобиля" },
    { pt: "ISV", context: "Imposto Sobre Veículos", ru: "налог на регистрацию автомобиля в Португалии" },
    { pt: "IPO", context: "Inspeção Periódica Obrigatória", ru: "обязательный техосмотр" },
    { pt: "seguro automóvel", ru: "ОСАГО / обязательная страховка авто" },
    { pt: "transferência de propriedade", ru: "перерегистрация собственности в IMT" },
    { pt: "Via Verde", ru: "электронная оплата платных дорог" },
    { pt: "leasing operacional", ru: "операционный лизинг — долгосрочная аренда с обслуживанием" },
    { pt: "registo automóvel", ru: "реестр авто; проверка залогов и ограничений" },
    { pt: "Standvirtual", ru: "крупнейшая площадка объявлений о продаже авто в PT" },
  ],
  "zamena-voditelskih-prav-portugaliya-2026": [
    { pt: "troca de carta de condução", ru: "обмен иностранных прав на португальские" },
    { pt: "carta de condução", ru: "водительское удостоверение" },
    { pt: "IMT", context: "Instituto da Mobilidade e dos Transportes", ru: "орган, выдающий права и регистрирующий авто" },
    { pt: "autorização de residência", ru: "разрешение на проживание (ВНЖ); от неё отсчитываются сроки обмена" },
    { pt: "convenções internacionais", ru: "международные соглашения о признании ВУ" },
    { pt: "código 794", ru: "ограничение срока прав датой окончания ВНЖ" },
    { pt: "RESPER", ru: "реестр водителей IMT" },
    { pt: "exame de condução", ru: "практический экзамен по вождению" },
    { pt: "Centro de Exames", ru: "центр сдачи теории и практики" },
    { pt: "fixar residência", ru: "официально зафиксировать место жительства в PT" },
  ],
  "nif-lissabon-chto-puutayut": [
    { pt: "NIF", context: "Número de Identificação Fiscal", ru: "налоговый номер физлица или компании" },
    { pt: "Finanças", ru: "налоговая служба; Portal das Finanças — личный кабинет" },
    { pt: "Loja do Cidadão", ru: "государственный центр услуг «магазин гражданина»" },
    { pt: "representante fiscal", ru: "налоговый представитель для нерезидента без EU-адреса" },
    { pt: "comprovativo de morada", ru: "подтверждение адреса для NIF и банка" },
    { pt: "e-Fatura", ru: "портал электронных счетов-фактур" },
    { pt: "Senha das Finanças", ru: "пароль доступа к налоговому кабинету" },
    { pt: "AT", context: "Autoridade Tributária", ru: "налоговая администрация Португалии" },
    { pt: "NIPC", ru: "налоговый номер юрлица (аналог NIF для компаний)" },
    { pt: "certidão", ru: "официальная справка/выписка из реестра" },
  ],
  "aima-agora-zapis-2026": [
    { pt: "AIMA", context: "Agência para a Integração, Migrações e Asilo", ru: "миграционное агентство (замена SEF)" },
    { pt: "Agora", ru: "портал онлайн-записи AIMA для imigrantes" },
    { pt: "agendamento", ru: "запись на приём в AIMA" },
    { pt: "autorização de residência", ru: "разрешение на проживание" },
    { pt: "título de residência", ru: "пластиковая карта ВНЖ" },
    { pt: "manifestação de interesse", ru: "заявление о намерении получить ВНЖ (legacy-процедура)" },
    { pt: "taxa", ru: "госпошлина за услугу миграции" },
    { pt: "comprovativo de agendamento", ru: "подтверждение записи — часто достаточно для банка и аренды" },
    { pt: "balcão", ru: "окно приёма в AIMA / Loja do Cidadão" },
    { pt: "renovação", ru: "продление ВНЖ" },
  ],
  "arenda-lissabon-do-podpisi": [
    { pt: "contrato de arrendamento", ru: "договор аренды жилья" },
    { pt: "caução", ru: "залог арендодателю (обычно 1–2 месяца)" },
    { pt: "renda", ru: "ежемесячная арендная плата" },
    { pt: "fiador", ru: "поручитель по договору аренды" },
    { pt: "registo do contrato", ru: "регистрация договора в Finanças (обязательна)" },
    { pt: "certidão permanente", ru: "выписка о собственнике из реестра недвижимости" },
    { pt: "condomínio", ru: "плата за содержание многоквартирного дома" },
    { pt: "IMI", ru: "муниципальный налог на недвижимость (обычно платит владелец)" },
    { pt: "quinta propriedade", ru: "справка о праве собственности на квартиру" },
    { pt: "Idealista", ru: "крупнейший портал объявлений об аренде и продаже" },
  ],
  "arenda-kvartiry-lisbon-pervyi-mesyac-2026": [
    { pt: "arrendamento", ru: "аренда жилья" },
    { pt: "senhorio", ru: "арендодатель" },
    { pt: "inquilino", ru: "арендатор" },
    { pt: "caução", ru: "депозит при заселении" },
    { pt: "recibo de renda", ru: "квитанция об оплате аренды" },
    { pt: "contrato", ru: "договор; без registo в Finanças — риск для обеих сторон" },
    { pt: "mobiliado", ru: "меблированная квартира" },
    { pt: "T0 / T1 / T2", ru: "типология: студия / 1-спальня / 2-спальни" },
    { pt: "freguesia", ru: "приход / административный район города" },
    { pt: "comprovativo de morada", ru: "документ для подтверждения адреса (NIF, SNS, банк)" },
  ],
  "kak-otkryt-bankovskiy-schet-portugalia-2026": [
    { pt: "NIB", ru: "банковский идентификатор счёта (21 цифра)" },
    { pt: "IBAN", ru: "международный номер счёта PT50…" },
    { pt: "Multibanco", ru: "сеть банкоматов и платёжная система PT" },
    { pt: "comprovativo de morada", ru: "подтверждение адреса — обязательный документ для счёта" },
    { pt: "comprovativo de rendimentos", ru: "справка о доходах" },
    { pt: "KYC", ru: "идентификация клиента; банк проверяет происхождение средств" },
    { pt: "conta à ordem", ru: "текущий расчётный счёт" },
    { pt: "conta poupança", ru: "сберегательный счёт" },
    { pt: "MB Way", ru: "мобильные платежи через приложение банка" },
    { pt: "extrato bancário", ru: "выписка по счёту" },
  ],
  "otkrytie-scheta-kreditnaya-karta-portugaliya-2026": [
    { pt: "cartão de crédito", ru: "кредитная карта" },
    { pt: "cartão de débito", ru: "дебетовая карта, привязанная к счёту" },
    { pt: "limite de crédito", ru: "кредитный лимит по карте" },
    { pt: "Central de Responsabilidades de Crédito", ru: "бюро кредитных историй Banco de Portugal" },
    { pt: "IRS", ru: "декларация подоходного налога; банки могут запросить" },
    { pt: "recibos de vencimento", ru: "расчётные листы с работы" },
    { pt: "conta conjunta", ru: "совместный счёт" },
    { pt: "comprovativo de IBAN", ru: "справка с реквизитами счёта" },
    { pt: "anuidade", ru: "годовое обслуживание карты" },
    { pt: "3D Secure", ru: "подтверждение онлайн-платежей через SMS/app" },
  ],
  "sns-registration-changes-2026": [
    { pt: "SNS", context: "Serviço Nacional de Saúde", ru: "национальная система здравоохранения" },
    { pt: "utente", ru: "зарегистрированный пациент SNS" },
    { pt: "número de utente", ru: "номер пациента в SNS" },
    { pt: "centro de saúde", ru: "поликлиника / центр первичной помощи по району" },
    { pt: "médico de família", ru: "участковый терапевт" },
    { pt: "ADSE", ru: "доп. медстрахование для госслужащих; иногда путают с SNS" },
    { pt: "taxa moderadora", ru: "символическая доплата за приём в SNS" },
    { pt: "receita médica", ru: "рецепт врача" },
    { pt: "Cartão Europeu de Seguro de Doença", ru: "европейская карта медстрахования (EHIC)" },
    { pt: "inscrição", ru: "регистрация в centro de saúde" },
  ],
  "smena-adresa-nif-financas-2026": [
    { pt: "alteração de morada", ru: "смена адреса в налоговой" },
    { pt: "Finanças", ru: "Portal das Finanças — личный кабинет налогоплательщика" },
    { pt: "comprovativo de morada", ru: "новый документ, подтверждающий адрес" },
    { pt: "freguesia", ru: "район; адрес привязан к freguesia в NIF" },
    { pt: "código postal", ru: "почтовый индекс (формат 0000-000)" },
    { pt: "certidão de domicílio fiscal", ru: "справка о налоговом адресе" },
    { pt: "Senha das Finanças", ru: "пароль для входа в кабинет" },
    { pt: "Chave Móvel Digital", ru: "государственная цифровая подпись (CMD)" },
    { pt: "AT", context: "Autoridade Tributária", ru: "налоговая администрация" },
    { pt: "morada fiscal", ru: "адрес для налоговых целей" },
  ],
  "pervyj-mesyac-portugaliya-checklist": [
    { pt: "NIF", ru: "налоговый номер — первый документ для банка и аренды" },
    { pt: "NISS", context: "Número de Identificação da Segurança Social", ru: "номер соцстраха" },
    { pt: "Segurança Social", ru: "служба социального обеспечения" },
    { pt: "utente SNS", ru: "регистрация в системе здравоохранения" },
    { pt: "comprovativo de morada", ru: "подтверждение адреса" },
    { pt: "Viva Viagem / Andante", ru: "проездные карты общественного транспорта Lisboa/Porto" },
    { pt: "EPAL / Águas do Porto", ru: "водоканал — оформление на имя жильца" },
    { pt: "EDP / Iberdrola", ru: "поставщики электричества" },
    { pt: "IMI", ru: "налог на недвижимость; при аренде обычно не ваш" },
    { pt: "Loja do Cidadão", ru: "единое окно госуслуг" },
  ],
  "vybor-internet-provaydera-portugaliya-2026": [
    { pt: "fibra ótica", ru: "оптоволоконный интернет" },
    { pt: "pacote", ru: "пакет услуг: интернет + TV + telemóvel" },
    { pt: "router", ru: "маршрутизатор; часто аренда включена в контракт" },
    { pt: "fidelização", ru: "минимальный срок контракта (обычно 12–24 мес.)" },
    { pt: "MEO / NOS / Vodafone", ru: "три основных оператора фикс+мобайл в PT" },
    { pt: "Nowo / Digi", ru: "альтернативные операторы с конкурентными тарифами" },
    { pt: "instalação", ru: "подключение и монтаж линии" },
    { pt: "cobertura", ru: "зона покрытия fibra по адресу" },
    { pt: "tarifário", ru: "тарифный план" },
    { pt: "ANACOM", ru: "регулятор связи; сравнение тарифов на anacom.pt" },
  ],
  "termo-responsabilidade-podtverzhdenie-zhilya-2026": [
    { pt: "termo de responsabilidade", ru: "декларация-поручительство о предоставлении жилья" },
    { pt: "comprovativo de morada", ru: "документ, подтверждающий адрес проживания" },
    { pt: "declaração", ru: "заявление/декларация на бланке или в Finanças" },
    { pt: "anfitrião", ru: "принимающая сторона — владелец жилья или арендодатель" },
    { pt: "carta convite", ru: "приглашение для визы; не заменяет termo для NIF" },
    { pt: "registo de alojamento", ru: "регистрация проживания (SEF/AIMA legacy)" },
    { pt: "Finanças", ru: "для NIF termo часто подают вместе с morada" },
    { pt: "autenticação", ru: "заверение подписи у advogado / notário / Câmara" },
    { pt: "morada", ru: "адрес проживания в документах" },
    { pt: "atestado de residência", ru: "справка о проживании от freguesia" },
  ],
  "poisk-mestnyh-uslug-portugaliya-2026": [
    { pt: "prestador de serviços", ru: "исполнитель услуг (мастер, клининг, ремонт)" },
    { pt: "orçamento", ru: "смета / коммерческое предложение до начала работ" },
    { pt: "fatura", ru: "официальный счёт-фактура с NIF" },
    { pt: "recibo verde", ru: "квитанция самозанятого (trabalhador independente)" },
    { pt: "IVA", ru: "НДС; на fatura указывается отдельной строкой" },
    { pt: "OLX / Fixando", ru: "площадки поиска мастеров и услуг" },
    { pt: "referências", ru: "рекомендации от соседей или expat-чатов" },
    { pt: "caução", ru: "предоплата; осторожно при работе с незнакомыми" },
    { pt: "garantia", ru: "гарантия на выполненные работы" },
    { pt: "NIF", ru: "налоговый номер исполнителя — проверяйте на fatura" },
  ],
  "lgoty-s-vnj-kulturnye-mesta-2026": [
    { pt: "título de residência", ru: "карта ВНЖ — даёт право на льготные тарифы" },
    { pt: "cartão de cidadão", ru: "удостоверение гражданина PT; у иностранцев — titre de résident" },
    { pt: "desconto", ru: "скидка для резидентов" },
    { pt: "bilhete", ru: "билет в музей / транспорт" },
    { pt: "NIF", ru: "иногда просят вместе с ВНЖ для оформления льготы" },
    { pt: "comprovativo de residência", ru: "подтверждение статуса резидента" },
    { pt: "DGARTES", ru: "управление искусств; часть программ льгот" },
    { pt: "CP", context: "Comboios de Portugal", ru: "железная дорога; карты и абонементы для резидентов" },
    { pt: "Metro do Porto / Metropolitano de Lisboa", ru: "метро; отдельные тарифы nº de utente" },
    { pt: "Biblioteca Municipal", ru: "муниципальная библиотека — часто бесплатный абонемент" },
  ],
  "vozvrat-remont-tovarov-portugaliya-2026": [
    { pt: "devolução", ru: "возврат товара продавцу" },
    { pt: "garantia", ru: "гарантия производителя/продавца" },
    { pt: "livro de reclamações", ru: "книга жалоб — обязательна у всех продавцов услуг" },
    { pt: "fatura", ru: "чек/счёт — без него возврат сложнее" },
    { pt: "prazo de devolução", ru: "срок возврата (14 дней онлайн по EU-правилам)" },
    { pt: "DECO PROteste", ru: "общество защиты прав потребителей PT" },
    { pt: "ASAE", ru: "служба экономической и продовольственной безопасности" },
    { pt: "defeito de fabrico", ru: "заводской брак" },
    { pt: "reparação", ru: "ремонт по гарантии" },
    { pt: "reembolso", ru: "возврат денег" },
  ],
  "poterya-pitomtsa-portugaliya-gid-2026": [
    { pt: "animal de companhia", ru: "домашнее животное" },
    { pt: "microchip", ru: "чип идентификации — обязателен для собак" },
    { pt: "DGAV", context: "Direção-Geral de Alimentação e Veterinária", ru: "ветеринарный регулятор" },
    { pt: "canil / gatil", ru: "приют для собак / кошек" },
    { pt: "SIAC", ru: "реестр идентифицированных животных" },
    { pt: "vacinas", ru: "прививки; rabies обязательна для собак" },
    { pt: "licença", ru: "лицензия на содержание (зависит от concelho)" },
    { pt: "seguro de responsabilidade civil", ru: "страхование ответственности владельца собаки" },
    { pt: "anúncio", ru: "объявление о пропаже — OLX, Facebook, veterinários" },
    { pt: "CCF", context: "Centro Nacional de Comunicação de Animais de Companhia", ru: "центр учёта пропавших животных" },
  ],
  "studencheskiy-vnzh-portugal-mify-aima-2026": [
    { pt: "autorização de residência para estudo", ru: "ВНЖ для учёбы" },
    { pt: "D7 / D8 / D2", ru: "типы виз для резидентов (доход / digital nomad / бизнес)" },
    { pt: "AIMA", ru: "миграционное агентство — выдаёт и продлевает ВНЖ" },
    { pt: "comprovativo de meios de subsistência", ru: "подтверждение средств к существованию" },
    { pt: "matrícula", ru: "зачисление в учебное заведение" },
    { pt: "instituição de ensino superior", ru: "высшее учебное заведение" },
    { pt: "declaração da escola", ru: "справка от школы/вуза для AIMA" },
    { pt: "taxa de processo", ru: "пошлина за рассмотрение заявки" },
    { pt: "renovação", ru: "продление студенческого ВНЖ" },
    { pt: "SEF", ru: "старое название миграционной службы (до AIMA)" },
  ],
  "ciple-guide-2026": [
    { pt: "CIPLE", context: "Certificado Inicial de Português Língua Estrangeira", ru: "экзамен португальского уровня A2" },
    { pt: "CAPLE", ru: "центр сертификации португальского как иностранного (ULisboa)" },
    { pt: "SEF / AIMA", ru: "для гражданства и части ВНЖ нужен сертификат A2" },
    { pt: "inscrição", ru: "регистрация на экзамен через caple.letras.ulisboa.pt" },
    { pt: "taxa de exame", ru: "экзаменационный сбор" },
    { pt: "compreensão oral / escrita", ru: "аудирование / чтение — части экзамена" },
    { pt: "produção e interação orais", ru: "устная часть и диалог" },
    { pt: "produção escrita", ru: "письменная часть" },
    { pt: "centro de exames", ru: "аккредитованный центр сдачи CAPLE" },
    { pt: "diploma de português", ru: "сертификат — храните оригинал для AIMA/Conservatória" },
  ],
  "porto-vs-braga-semya-mezhdunarodnaya-shkola-2026": [
    { pt: "freguesia", ru: "район/приход города; привязка morada и catchment школы" },
    { pt: "agrupamento escolar", ru: "объединение школ района; matrícula в escola pública" },
    { pt: "comprovativo de morada", ru: "подтверждение адреса для школы, NIF и SNS" },
    { pt: "contrato de arrendamento", ru: "договор аренды; с registo в Finanças — morada" },
    { pt: "Andante", ru: "проездной Metro do Porto / автобусы зоны Grande Porto" },
    { pt: "catchment", ru: "зона школы по адресу проживания" },
    { pt: "school bus", ru: "школьный автобус international school" },
    { pt: "GEC", context: "Gabinete de Educação e Cidadania", ru: "муниципальное управление образования concelho" },
    { pt: "matrícula", ru: "зачисление ребёнка в школу" },
    { pt: "waiting list", ru: "лист ожидания мест в international school" },
  ],
  "pokupka-zemli-postroyka-doma-norte-portugaliya-2026": [
    { pt: "PDM", context: "Plano Director Municipal", ru: "муниципальный генеральный план застройки" },
    { pt: "solo urbano", ru: "земля в городской зоне — строительство при соблюдении PDM" },
    { pt: "solo rustico", ru: "сельхоз/лесная зона — жилое строительство ограничено" },
    { pt: "licença de construção", ru: "разрешение на строительство от Câmara Municipal" },
    { pt: "certidão de informação urbanística", ru: "справка муниципалитета: можно ли строить на участке" },
    { pt: "topógrafo", ru: "геодезист; съёмка границ и привязка к PDM" },
    { pt: "arquiteto", ru: "архитектор OA; проект и подача licença" },
    { pt: "empreiteiro", ru: "подрядчик строительства с alvará" },
    { pt: "IMT", context: "Imposto Municipal sobre Transmissões", ru: "налог на передачу недвижимости/земли" },
    { pt: "licença de utilização", ru: "разрешение на ввод дома в эксплуатацию (habitação)" },
  ],
  "klimat-norte-zhara-vlazhnost-plesen-zima-2026": [
    { pt: "humidade", ru: "влажность воздуха и стен; в Norte атлантическая, осень–весна 80–95%" },
    { pt: "bolor", ru: "плесень; риск для дыхания по DGS, нужно устранять источник, не только красить" },
    { pt: "ar condicionado", ru: "кондиционер; split — только instalador certificado DGEG" },
    { pt: "desumidificador", ru: "осушитель воздуха; €150–350, расход €15–30/мес в сыром сезоне" },
    { pt: "isolamento", ru: "теплоизоляция; в старых prédios Porto/Braga часто отсутствует" },
    { pt: "aquecimento", ru: "отопление; central heating редок, чаще bomba de calor или elétrico" },
    { pt: "bomba de calor", context: "heat pump", ru: "тепловой насос в AC — обогрев эффективнее resistência" },
    { pt: "condomínio", ru: "ТСЖ; aprovação assembleia для bloco exterior на varanda" },
    { pt: "ventilação", ru: "проветривание; при 90% humidade снаружи мало без desumidificador" },
    { pt: "ilhas de calor", ru: "острова тепла в городе; +4–6 °C в бетонном центре Porto" },
  ],
  "zamena-zagranpasporta-portugaliya-2026": [
    { pt: "passaporte", ru: "загранпаспорт / национальный паспорт страны гражданства" },
    { pt: "consulado", ru: "консульство; для RU/KZ — Lisboa, для UA — Lisboa или Porto" },
    { pt: "agendamento", ru: "предварительная запись на приём (lisboa.kdmid.ru и др.)" },
    { pt: "comprovativo de morada", ru: "подтверждение адреса проживания в Португалии" },
    { pt: "passaporte biométrico", ru: "биометрический загран РФ на 10 лет; фото в consulado" },
    { pt: "título de residência", ru: "пластиковая карта ВНЖ; срок часто короче заграна" },
    { pt: "apostila", ru: "апостиль на португальские документы для consulado РФ" },
    { pt: "proteção temporária", ru: "временная защита для граждан UA в PT" },
    { pt: "balcão", ru: "окно выдачи; готовый passaporte — общая очередь без записи" },
    { pt: "svidetelstvo na vozvrashchenie", ru: "свидетельство на возвращение в РФ при срочном выезде" },
  ],
  "elektromobil-tesla-v-portugalii-2026": [
    { pt: "carro elétrico", ru: "электромобиль; в документах IMT и страховке указывается тип de energia" },
    { pt: "ISV", context: "Imposto Sobre Veículos", ru: "налог при первой регистрации; для чистых EV = 0 €" },
    { pt: "IUC", context: "Imposto Único de Circulação", ru: "ежегодный дорожный налог; для чистых EV не начисляется" },
    { pt: "Mobi.E", ru: "национальная сеть публичных зарядных станций" },
    { pt: "CEME", ru: "коммерческий оператор зарядки; с 2025 прямой контракт не обязателен" },
    { pt: "carregador doméstico", ru: "домашняя зарядка (wallbox); в condomínio нужно согласование" },
    { pt: "condomínio", ru: "управление многоквартирного дома" },
    { pt: "autonomia", ru: "заявленный запас хода" },
    { pt: "Supercharger", ru: "сеть быстрых зарядок Tesla вдоль магистралей" },
    { pt: "Miio", ru: "агрегатор зарядок Mobi.E с картой и оплатой" },
  ],
};

export function glossaryForSlug(slug: string): GlossaryTerm[] | undefined {
  return EDITORIAL_GLOSSARIES[slug];
}
