/** Short Russian labels for /notes/{slug} cross-links in guide body text. */
export const NOTE_LINK_LABELS: Record<string, string> = {
  "pervyj-mesyac-portugaliya-checklist": "чеклист первого месяца",
  "nif-porto-kak-poluchit-2026": "гайд по NIF",
  "nif-lissabon-chto-puutayut": "гайд по NIF",
  "aima-agora-zapis-2026": "запись в AIMA",
  "prodlenie-vnzh-portugaliya-aima-2026": "продление ВНЖ AIMA",
  "arenda-kvartiry-lisbon-pervyi-mesyac-2026": "аренда в первый месяц",
  "arenda-lissabon-do-podpisi": "аренда до подписи",
  "mashina-portugaliya-kupit-arenda-import-2026": "гайд по машине",
  "platnye-dorogi-shtrafy-avariya-portugaliya-norte-2026": "платные дороги и штрафы",
  "mezhdunarodnye-shkoly-portugaliya-2026": "международные школы",
  "zamena-voditelskih-prav-portugaliya-2026": "обмен водительских прав",
  "zamena-zagranpasporta-portugaliya-2026": "замена загранпаспорта",
  "zapis-v-konsulstvo-portugaliya-2026": "запись в консульство",
  "nie-empadronamiento-poryadok-2026": "NIE и empadronamiento",
  "tie-cita-extranjeria-valencia-2026": "TIE и cita extranjería",
  "dnv-uge-konsulstvo-2026": "DNV и UGE",
  "zapis-konsulstvo-ispanija-pasport-2026": "запись GKS Barcelona",
  "arenda-valencia-idealista-2026": "аренда Valencia",
  "bank-iban-nerezident-ispaniya-2026": "банк и IBAN",
  "beckham-autonomo-mify-2026": "Beckham и autónomo",
  "pervye-30-dnej-v-ispanii-satelit-2026": "первые 30 дней в Испании",
  "sim-internet-luz-valencia-2026": "SIM, интернет и свет Valencia",
  "meditsina-valencia-sip-sns-chastnaya-2026": "медицина и SIP Valencia",
  "valencia-rajony-arenda-shkoly-metro-2026": "районы Valencia",
  "transport-valencia-metro-emt-coche-2026": "транспорт Valencia",
  "shkoly-semya-valencia-2026": "школы и семья Valencia",
  "zheltye-stranitsy-relokanta-valencia-2026": "жёлтые страницы Valencia",
  "klimat-byt-valencia-4-6-mes-2026": "климат и быт Valencia",
  "alta-ss-hacienda-valencia-2026": "alta SS и Hacienda Valencia",
  "pervye-30-dnej-v-italii-satelit-2026": "первые 30 дней в Италии",
  "codice-fiscale-milano-2026": "codice fiscale Milano",
  "sim-internet-luce-milano-2026": "SIM, интернет и свет Milano",
  "arenda-milano-idealista-2026": "аренда Milano",
  "permesso-questura-milano-2026": "permesso и Questura",
  "vnj-italiya-nomade-elective-2026": "nomade digitale и elective",
  "bank-iban-nerezident-italiya-2026": "банк и IBAN Италия",
  "meditsina-milano-ssn-tessera-2026": "SSN и tessera Milano",
  "milano-rajony-arenda-metro-como-2026": "районы Milano и Como",
  "transport-milano-atm-trenord-2026": "ATM и Trenord",
  "shkoly-semya-milano-como-2026": "школы Milano и Como",
  "zheltye-stranitsy-relokanta-milano-2026": "жёлтые страницы Milano",
  "zapis-konsulstvo-italiya-pasport-2026": "консульство RF Milano",
  "inps-partita-iva-milano-2026": "INPS и partita IVA",
  "klimat-byt-milano-nord-como-2026": "климат и быт Milano Nord",
  "arenda-dolgosrok-porto-braga-2026": "аренда Porto/Braga",
  "turizm-vnutri-portugalii-norte-2026": "внутренний туризм PT",
  "porto-vs-braga-semya-mezhdunarodnaya-shkola-2026": "Порту vs Брага",
  "klimat-norte-zhara-vlazhnost-plesen-zima-2026": "климат Norte",
  "zheltye-stranitsy-relokanta-portugaliya-2026": "жёлтые страницы релоканта",
  "kak-otkryt-bankovskiy-schet-portugalia-2026": "открытие счёта и кредитка",
  "otkrytie-scheta-kreditnaya-karta-portugaliya-2026": "открытие счёта и кредитка",
  "kupit-kvartiru-portugaliya-norte-2026": "покупка квартиры Norte",
  "pokupka-zemli-postroyka-doma-norte-portugaliya-2026": "земля и постройка дома",
  "regiony-portugalii-ekspaty-klimat-tseny-2026": "регионы Португалии",
  "portugal-destination-tips-regiony-2026": "атлас поездок по PT",
  "put-santyago-porto-camino-portugues-2026": "Путь Сантьяго из Порту",
};

export function noteLinkLabel(slug: string): string {
  return NOTE_LINK_LABELS[slug] ?? "подробнее";
}
