/**
 * Generates supabase/migrations/20260625260000_student_visa_programs.sql
 * from lib/corridor/seed/study-programs.ts
 *
 * Run: npx tsx scripts/generate-study-programs-sql.ts
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { STUDY_PROGRAMS, STUDY_WIZARD_QUESTIONS } from "../lib/corridor/seed/study-programs";

const OUT = join(process.cwd(), "supabase/migrations/20260625260000_student_visa_programs.sql");
const PASSPORTS = ["RU", "BY", "UA", "KZ"] as const;

function sqlStr(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlJson(obj: unknown): string {
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'`;
}

function main() {
  const lines: string[] = [
    "-- Student visa (STUDY) programs — PT, ES, DE, FR, IT",
    "-- Generated by scripts/generate-study-programs-sql.ts",
    "",
    "INSERT INTO emigro_program_types (code, label_en, label_ru) VALUES",
    "  ('STUDY', 'Study & university', 'Учёба / студенческая виза')",
    "ON CONFLICT (code) DO NOTHING;",
    "",
    "INSERT INTO emigro_programs (id, slug, destination_iso2, program_type, title_en, title_ru, summary_en, summary_ru) VALUES",
  ];

  STUDY_PROGRAMS.forEach((link, i) => {
    const p = link.program;
    const dest = p.destinationIso2 ?? "PT";
    lines.push(
      `  (${sqlStr(link.programId)}, ${sqlStr(p.slug)}, '${dest}', 'STUDY', ${sqlStr(p.titleEn)}, ${sqlStr(p.titleRu)}, ${sqlStr(p.summaryEn)}, ${sqlStr(p.summaryRu)})${i < STUDY_PROGRAMS.length - 1 ? "," : ""}`
    );
  });
  lines.push("ON CONFLICT (slug) DO NOTHING;");
  lines.push("");

  lines.push("INSERT INTO emigro_corridor_programs (corridor_id, program_id, sort_order, is_featured) VALUES");
  STUDY_PROGRAMS.forEach((link, i) => {
    lines.push(
      `  (${sqlStr(link.corridorId)}, ${sqlStr(link.programId)}, ${link.sortOrder}, false)${i < STUDY_PROGRAMS.length - 1 ? "," : ""}`
    );
  });
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  lines.push("INSERT INTO emigro_program_versions (id, program_id, version_label, eligibility_rule) VALUES");
  STUDY_PROGRAMS.forEach((link, i) => {
    lines.push(
      `  (${sqlStr(link.versionId)}, ${sqlStr(link.programId)}, '2026-06', ${sqlJson(link.program.rule)})${i < STUDY_PROGRAMS.length - 1 ? "," : ""}`
    );
  });
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  const reqRows: string[] = [];
  STUDY_PROGRAMS.forEach((link) => {
    link.program.requirements.forEach((r, ri) => {
      reqRows.push(
        `  (${sqlStr(link.versionId)}, '${r.type}', ${sqlStr(r.labelEn)}, ${sqlStr(r.labelRu)}, ${sqlStr(r.value)}, ${ri + 1})`
      );
    });
  });
  lines.push("INSERT INTO emigro_program_requirements (program_version_id, requirement_type, label_en, label_ru, value_text, sort_order) VALUES");
  lines.push(reqRows.join(",\n"));
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  const costRows: string[] = [];
  STUDY_PROGRAMS.forEach((link) => {
    link.program.costs.forEach((c, ci) => {
      costRows.push(
        `  (${sqlStr(link.versionId)}, ${sqlStr(c.labelEn)}, ${sqlStr(c.labelRu)}, ${sqlStr(c.amount)}, ${ci + 1})`
      );
    });
  });
  lines.push("INSERT INTO emigro_program_costs (program_version_id, label_en, label_ru, amount_text, sort_order) VALUES");
  lines.push(costRows.join(",\n"));
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  const tlRows: string[] = [];
  STUDY_PROGRAMS.forEach((link) => {
    link.program.timeline.forEach((t, ti) => {
      tlRows.push(
        `  (${sqlStr(link.versionId)}, '${t.step}', ${sqlStr(t.titleEn)}, ${sqlStr(t.titleRu)}, ${sqlStr(t.duration)}, ${ti + 1})`
      );
    });
  });
  lines.push("INSERT INTO emigro_program_timeline_steps (program_version_id, step_type, title_en, title_ru, duration_text, sort_order) VALUES");
  lines.push(tlRows.join(",\n"));
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  const srcRows: string[] = [];
  STUDY_PROGRAMS.forEach((link) => {
    link.program.sources.forEach((s) => {
      srcRows.push(
        `  (${sqlStr(link.versionId)}, ${sqlStr(s.url)}, ${sqlStr(s.excerpt)}, '2026-06-25', ${sqlStr(s.labelEn)}, ${sqlStr(s.labelRu)})`
      );
    });
  });
  lines.push("INSERT INTO emigro_program_sources (program_version_id, source_url, raw_excerpt, last_verified, label_en, label_ru) VALUES");
  lines.push(srcRows.join(",\n"));
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  const peRows: string[] = [];
  STUDY_PROGRAMS.forEach((link) => {
    PASSPORTS.forEach((passport) => {
      const status = passport === "RU" ? "eligible" : "partial";
      const notesEn =
        passport === "RU"
          ? "Official program requirements verified; apply via consulate/VFS where available"
          : "Preliminarily possible, subject to consulate jurisdiction and place of submission";
      const notesRu =
        passport === "RU"
          ? "Официальные требования программы проверены; подача через консульство/VFS где доступно"
          : "Предварительно возможно, но зависит от консульства подачи и юрисдикции";
      peRows.push(
        `  (${sqlStr(link.versionId)}, '${passport}', '${status}', ${sqlStr(notesEn)}, ${sqlStr(notesRu)})`
      );
    });
  });
  lines.push("INSERT INTO emigro_passport_eligibility (program_version_id, passport_iso2, status, notes_en, notes_ru) VALUES");
  lines.push(peRows.join(",\n"));
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  lines.push("INSERT INTO emigro_wizard_modules (id, wizard_id, module_key, title_en, title_ru, sort_order) VALUES");
  STUDY_PROGRAMS.forEach((link, i) => {
    lines.push(
      `  (${sqlStr(link.studyModuleId)}, ${sqlStr(link.wizardId)}, 'study', 'Study route', 'Учёба', 5)${i < STUDY_PROGRAMS.length - 1 ? "," : ""}`
    );
  });
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  const qRows: string[] = [];
  STUDY_PROGRAMS.forEach((link) => {
    STUDY_WIZARD_QUESTIONS.forEach((q, qi) => {
      const helpEn = "helpEn" in q ? q.helpEn : undefined;
      const helpRu = "helpRu" in q ? q.helpRu : undefined;
      qRows.push(
        `  (${sqlStr(link.studyModuleId)}, '${q.key}', '${q.type}', ${sqlStr(q.labelEn)}, ${sqlStr(q.labelRu)}, ${helpEn ? sqlStr(helpEn) : "NULL"}, ${helpRu ? sqlStr(helpRu) : "NULL"}, ${"options" in q && q.options ? sqlStr(q.options) : "NULL"}, ${qi + 1})`
      );
    });
  });
  lines.push("INSERT INTO emigro_wizard_questions (module_id, question_key, question_type, label_en, label_ru, help_en, help_ru, options, sort_order) VALUES");
  lines.push(qRows.join(",\n"));
  lines.push("ON CONFLICT DO NOTHING;");
  lines.push("");

  lines.push(`INSERT INTO emigro_corridor_digest_items (corridor_id, category, title_en, title_ru, body_en, body_ru, source_url, last_verified, sort_order) VALUES`);
  lines.push(
    `  ('a0000000-0000-4000-8000-000000000001', 'practical', 'D4 student visa', 'Студенческая виза D4', 'National D4 visa for enrollment at a Portuguese university or school. Limited part-time work allowed. See program page for 2026 means threshold.', 'Национальная виза D4 при зачислении в португальский вуз или школу. Ограниченное право подработки. Пороги средств — на странице программы.', 'https://vistos.mne.gov.pt/en/national-visas/general-information/study-visa', '2026-06-25', 6)`
  );
  lines.push("ON CONFLICT DO NOTHING;");

  const sql = lines.join("\n") + "\n";
  writeFileSync(OUT, sql, "utf8");
  console.log(`Wrote ${OUT} (${sql.split("\n").length} lines, ${STUDY_PROGRAMS.length} programs)`);
}

main();
