const ISO2_TO_COUNTRY_RU: Record<string, string> = {
  AE: "ОАЭ",
  AM: "Армения",
  AT: "Австрия",
  AZ: "Азербайджан",
  BE: "Бельгия",
  BG: "Болгария",
  BY: "Беларусь",
  CH: "Швейцария",
  CY: "Кипр",
  CZ: "Чехия",
  DE: "Германия",
  DK: "Дания",
  EE: "Эстония",
  ES: "Испания",
  FI: "Финляндия",
  FR: "Франция",
  GB: "Великобритания",
  GE: "Грузия",
  GR: "Греция",
  HR: "Хорватия",
  HU: "Венгрия",
  IE: "Ирландия",
  IL: "Израиль",
  IT: "Италия",
  KG: "Киргизия",
  KZ: "Казахстан",
  LT: "Литва",
  LU: "Люксембург",
  LV: "Латвия",
  MD: "Молдова",
  MT: "Мальта",
  NL: "Нидерланды",
  NO: "Норвегия",
  PL: "Польша",
  PT: "Португалия",
  RO: "Румыния",
  RS: "Сербия",
  RU: "Россия",
  SE: "Швеция",
  SK: "Словакия",
  TR: "Турция",
  UA: "Украина",
  US: "США",
  UZ: "Узбекистан",
};

export function iso2ToCountryRu(iso2?: string | null): string | undefined {
  if (!iso2) return undefined;
  return ISO2_TO_COUNTRY_RU[iso2.trim().toUpperCase()];
}
